// Generates REVIEW.md, the human review queue. Usage: node scripts/build-review.mjs
//
// Every topic, dependency and relation in data/ is agent-authored and nobody has read it yet. This
// script lists all of them, grouped by the fragment that contributed them, so a reviewer can work
// through the corpus and record calls in data/review.json. REVIEW.md is regenerated from those
// decisions, so it is safe to rebuild at any time and must never be edited by hand.
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { depKey, passageList, relationKey, topicKey } from './lib/edge-key.mjs';
import { quoteOverlap } from './lib/overlap.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dataPath = (f) => join(root, 'data', f);
const load = (f) => JSON.parse(readFileSync(dataPath(f), 'utf8'));

const topics = load('topics.json').topics;
const deps = load('dependencies.json').dependencies;
const rels = load('relations.json').relations;
const decisions = load('review.json').decisions ?? {};
const kjvText = load('kjv.json').verses;

const nameOf = new Map(topics.map((t) => [t.id, t.name]));
const cell = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();
const statusOf = (key) => decisions[key]?.status ?? 'unreviewed';

// Attribute each item to the fragment that contributed it. A fragment names topics by slug and
// relations by endpoint pair, so anything left over was authored straight into data/.
const mergedDir = join(root, 'fragments', 'merged');
const batches = [];
const pairOf = (from, to, kind) => `${from}|${to}|${kind}`;
const byPair = new Map();
for (const r of rels) {
  const k = pairOf(r.from, r.to, r.kind);
  if (!byPair.has(k)) byPair.set(k, []);
  byPair.get(k).push(relationKey(r));
}

const claim = { topic: new Set(), dependency: new Set(), relation: new Set() };
for (const f of readdirSync(mergedDir).filter((x) => x.endsWith('.json')).sort()) {
  const frag = JSON.parse(readFileSync(join(mergedDir, f), 'utf8'));
  const b = { file: `fragments/merged/${f}`, topics: [], dependencies: [], relations: [] };
  for (const t of frag.topics ?? []) {
    const id = t2id(t.id);
    if (!claim.topic.has(id)) { claim.topic.add(id); b.topics.push(id); }
  }
  for (const d of frag.dependencies ?? []) {
    const key = depKey({ topicId: t2id(d.topic), prerequisiteId: t2id(d.prereq) });
    if (!claim.dependency.has(key)) { claim.dependency.add(key); b.dependencies.push(key); }
  }
  // A pair can carry several edges with different refs, so claim all of them.
  for (const r of frag.relations ?? []) {
    for (const key of byPair.get(pairOf(t2id(r.from), t2id(r.to), r.kind)) ?? []) {
      if (!claim.relation.has(key)) { claim.relation.add(key); b.relations.push(key); }
    }
  }
  batches.push(b);
}
function t2id(s) { return s.startsWith('bt_') ? s : `bt_${s}`; }

const direct = { file: 'authored directly in data/', topics: [], dependencies: [], relations: [] };
for (const t of topics) if (!claim.topic.has(t.id)) direct.topics.push(t.id);
for (const d of deps) if (!claim.dependency.has(depKey(d))) direct.dependencies.push(depKey(d));
for (const r of rels) if (!claim.relation.has(relationKey(r))) direct.relations.push(relationKey(r));
if (direct.topics.length || direct.dependencies.length || direct.relations.length) batches.push(direct);

const depByKey = new Map(deps.map((d) => [depKey(d), d]));
const relByKey = new Map(rels.map((r) => [relationKey(r), r]));
const topicById = new Map(topics.map((t) => [t.id, t]));

// Risk first: quotation edges whose cited passages share no wording at all. Measured, not guessed,
// and it is how the Isaiah 58 / Luke 4 mistake was caught.
const suspect = rels
  .map((r) => ({ r, ov: quoteOverlap(kjvText, r.kind, r.refs) }))
  .filter((x) => x.ov && x.ov.ratio === 0);

const counts = (items) => items.filter((i) => statusOf(i) !== 'unreviewed').length;
const out = [];
const w = (s = '') => out.push(s);

w('# Human review queue');
w();
w('> Generated by `npm run build:review` from `data/review.json` and the fragments in `fragments/merged/`. Do not edit by hand.');
w('>');
w('> Everything listed here was drafted by an agent from the KJV text and has not been read by a person. Rule zero in `PROVENANCE.md` is that nothing is made up, so this file is the check on that claim.');
w();
w('## Recording a decision');
w();
w('Edit `data/review.json`, then run `npm run build:review`. Keys are printed in the last column of each table.');
w();
w('```json');
w('"topic:bt_gen_creation": { "status": "ok", "by": "david", "on": "2026-10-05" },');
w(`"relation:${relationKey(suspect[0]?.r ?? rels[0])}": {`);
w('  "status": "wrong", "by": "david", "on": "2026-10-05",');
w('  "note": "What was wrong, and what was done about it."');
w('}');
w('```');
w();
w('`status` is `ok`, `changed` or `wrong`. `changed` and `wrong` require `by`, `on` and a `note` saying what was wrong. Removing an item from `data/` leaves its key behind; `npm run validate` warns about keys that no longer resolve.');
w();
w('## Progress');
w();
const total = topics.length + deps.length + rels.length;
const done = counts(topics.map((t) => topicKey(t.id))) + counts(deps.map(depKey)) + counts(rels.map(relationKey));
w(`${done} of ${total} items reviewed (${((done / total) * 100).toFixed(1)}%).`);
w();
w('| Batch | Topics | Deps | Relations | Reviewed |');
w('|---|---:|---:|---:|---:|');
for (const b of batches) {
  const items = [...b.topics.map(topicKey), ...b.dependencies, ...b.relations];
  w(`| \`${b.file}\` | ${b.topics.length} | ${b.dependencies.length} | ${b.relations.length} | ${counts(items)}/${items.length} |`);
}
w();
w(`Quotation edges sharing no content words: **${suspect.length}**. Each needs a decision before the surrounding batch can be signed off.`);
w();
w('| Edge | Cites | Shared words | Status | Key |');
w('|---|---|---:|---|---|');
for (const { r, ov } of suspect) {
  const key = relationKey(r);
  w(`| ${cell(nameOf.get(r.from))} -> ${cell(nameOf.get(r.to))} (${r.kind}) | ${cell(passageList(r.refs))} | 0 of ${ov.of} | ${statusOf(key)} | \`${key}\` |`);
}
w();
for (const b of batches) {
  const items = [...b.topics.map(topicKey), ...b.dependencies, ...b.relations];
  const left = items.filter((i) => statusOf(i) === 'unreviewed').length;
  w(`## \`${b.file}\``);
  w();
  w(`${items.length} items, ${left} still unreviewed.`);
  w();
  if (b.topics.length) {
    w('<details>');
    w(`<summary>Topics (${b.topics.length})</summary>`);
    w();
    w('| Id | Name | Type | Passages | Status | Key |');
    w('|---|---|---|---|---|---|');
    for (const id of b.topics) {
      const t = topicById.get(id);
      const key = topicKey(id);
      w(`| \`${id}\` | ${cell(t.name)} | ${t.type} | ${cell(passageList(t.primaryPassages))} | ${statusOf(key)} | \`${key}\` |`);
    }
    w();
    w('</details>');
    w();
  }
  if (b.dependencies.length) {
    w('<details>');
    w(`<summary>Dependencies (${b.dependencies.length})</summary>`);
    w();
    w('| Topic | Prerequisite | Strength | Stated reason | Status | Key |');
    w('|---|---|---|---|---|---|');
    for (const key of b.dependencies) {
      const d = depByKey.get(key);
      w(`| \`${d.topicId}\` | \`${d.prerequisiteId}\` | ${d.strength} | ${cell(d.reason)} | ${statusOf(key)} | \`${key}\` |`);
    }
    w();
    w('</details>');
    w();
  }
  if (b.relations.length) {
    w('<details>');
    w(`<summary>Relations (${b.relations.length})</summary>`);
    w();
    w('| From | To | Kind | Refs | Status | Key |');
    w('|---|---|---|---|---|---|');
    for (const key of b.relations) {
      const r = relByKey.get(key);
      w(`| ${cell(nameOf.get(r.from))} | ${cell(nameOf.get(r.to))} | ${r.kind} | ${cell(passageList(r.refs))} | ${statusOf(key)} | \`${key}\` |`);
    }
    w();
    w('</details>');
    w();
  }
}

writeFileSync(join(root, 'REVIEW.md'), out.join('\n'));
console.log(`REVIEW.md written: ${total} items across ${batches.length} batches, ${suspect.length} quotation edges to check first`);